import Head from "next/head";
import Banner from "../components/Banner";
import Header from "../components/Header";
import ItemPanel from "../components/ItemPanel";
import Sidebar from "../components/Sidebar";
import data from "../data";

export default function Home() {
  const { products } = data;
  console.log(products);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:ital,wght@0,400;0,700;1,400&display=swap"
          rel="stylesheet"
        />
      </Head>
      <p class="md:space-x-1 space-y-1 md:space-y-0 mb-4">
        <a
          class="inline-block px-6 py-2.5 bg-blue-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out"
          data-bs-toggle="collapse"
          href="#collapseExample"
          role="button"
          aria-expanded="false"
          aria-controls="collapseExample"
        >
          Link with href
        </a>
        <button
          class="inline-block px-6 py-2.5 bg-blue-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#collapseExample"
          aria-expanded="false"
          aria-controls="collapseExample"
        >
          Button with data-bs-target
        </button>
      </p>
      <div class="collapse" id="collapseExample">
        <div class="block p-6 rounded-lg shadow-lg bg-white">
          Some placeholder content for the collapse component. This panel is
          hidden by default but revealed when the user activates the relevant
          trigger.
        </div>
      </div>
      <Header />

      <div className="flex h-screen">
        <Sidebar />
        <div className="w-4/5 flex-col min-h-fit">
          <Banner />
          <div className="flex-col h-4/5 ">
            {products.map((product) => (
              <ItemPanel key={product.id} product={product} />
            ))}
          </div>
        </div>
      </div>

      <div className="h-24 text-white items-center justify-center flex bg-slate-900">
        Footer
      </div>
    </div>
  );
}
